.github/settings.yml, README.md
Testing out brew install, I ran into a couple things which are addressed here
1) 404 when requesting the release artifact. While this can likely be achieved by passing some credentials to brew, we were planning on making this repo public anyway so I figured no better time than the present
2) [brew tap \<user\>/\<repo\>](https://docs.brew.sh/Taps) expects the repo name to be prefixed with `homebrew-`. This goes hand in hand putting the homebrew formula in a separate repo, which we chose not to do. You can however pass a URL to `brew tap` in which case brew handles the URL just fine.
=> Installation instructions and make repo public

internal/command/command.go, internal/command/hooks.go, internal/command/hooks_test.go
Ensures that the console IO is added to the main command by always setting the main command to interactive mode.
This change gives a more intuitive experience for commands, especially override commands where you would expect to see your command output (`psql -c 'select * from foo;'`) without adding any additional flags regarding output.
=> Ensure main command always streams to console

go.mod, go.sum, internal/command/command.go
Adds a template helper to parse JSON outputs. While a command could probably call out to something like jq to help, it would be nice to have the ability to parse JSON output baked in to the templating so we can do something like this:
```
Command: ["echo", "{\"user\": \"foo\"}"], ID: "credentials"
Command: ["echo", "{{ json .Outputs.credentials.Stdout \"user\" }}"]
```
[tidwall/gsjson](https://github.com/tidwall/gjson) is the library used
=> Add json getter as template helper

internal/command/command.go
When the plugin errors, it should show the actual failed command, not the template.
fixes #37
=> Show cmd args, not command template

cmd/forward.go, cmd/forward_test.go, internal/command/config.go, internal/command/run.go
Closes the port-forwarding connection when the command is finished unless the `--persist` flag is passed. This actually works a bit nicer than I had anticipated because blocking commands (`psql` w/ no `-c` flag) will block until they are finished and once finished, send a done msg. So now something like using `\q` will close the `psql` session and the forwarding tunnel together.
fixes #40
=> Close forwarding tunnel when command is finished

internal/command/command.go, internal/command/sensitive.go
Adds a new `sensitive` template function. When converting to an `*exec.Command`, the function is a noop. When the internal `render()` method is called with `showSensitive = false`, anything piped to `sensitive` is redacted. 
The package is a bit short of tests and definitely needs coverage for templating, this included.
=> Add `sensitive` templating function that prevents printing of sensitive info

cmd/forward.go
Adds the [Version](https://github.com/spf13/cobra/blob/master/user_guide.md#version-flag) field to the Cobra command, which allows users to bypass the minimum args requirement and print the version using `kubectl exec-forward version`
=> Add version field

.github/workflows/test.yml
Adds some caching on the Test workflow. This implementation takes the time down from 4:30 -> 2 minutes!
fixes #46
=> Add build/mod caching

README.md
Specifies the fully qualified formula in `install` rather than separately tapping
https://docs.brew.sh/Manpage#specifying-formulae
=> specify tap repo in `brew install`

cmd/forward.go
Adds shorthand versions of the flags added in the forward command.
```
arg: a
verbose: v
pod-timeout: t
persist: p
```
=> Add shorthand flags

cmd/forward_test.go, internal/command/command.go
Send interactive commands directly to the passed IO streams, rather than writing to both buffers and IO streams. This removes the option to read command output from other commands if the initial command is interactive. Interactive commands produce unstructured output and should not be relied upon to render subsequent commands.
=> Stream interactive commands to console (skip buffer capture)

internal/command/command.go, internal/command/command_test.go
The idea here is to `.Config` from templating in favor of the interesting portions of the config at the top level namespace (`.Config.LocalPort -> .LocalPort`)
=> Template portions of Config instead of the whole struct

internal/command/command.go, internal/command/command_test.go, internal/command/commands.go, internal/command/output.go, internal/command/outputs.go, internal/command/run.go
Removes the .Stdout/.Stderr path from the .Outputs templating path. There shouldn't be a need to us stderr in a subsequent command. As a result of the change, commands can use the command ID directly instead of `.Outputs.<id>.Stdout`
=> Remove stdout/stderr from templating

.github/workflows/lint.yml
The workflow name for linting has been bothering me, the name of the workflow should be what it does not the tool it uses.
=> Rename lint workflow

internal/command/args.go, internal/command/args_test.go, internal/command/command.go, internal/command/command_test.go, internal/command/commands.go, internal/command/run.go
Refactors the `Args` type:
* Creates an exported `ParseArgsFromAnnotations`. Clarifies purpose (parse args from an outer structure not just args) and prepares for `run.go` to be extracted from the package
* Removes overrides from the parsing method into a `Merge` method on `Args`
* Returns `map` not `*map` (https://dave.cheney.net/2017/04/30/if-a-map-isnt-a-reference-variable-what-is-it)
* Converts tests to table tests
* Adds coverage for invalid JSON
* Runs tests in parallel
I'll try to do more of these refactors as I add test coverage.
=> Refactor `Args` type

.github/settings.yml
Adds required checks for merging, making it easier to enable auto-merge for a PR
=> gh: require test/lint check to merge

internal/command/command.go, internal/command/command_test.go, internal/command/commands_test.go, internal/command/hooks.go
Refactors all the logic around parsing and templating commands:
* Passes around `TemplateData` to methods that need to render commands, as opposed to various members
* Replaces `Render` with `Name()` and `Args(data, options)`
* Adds test coverage for `Display`
* Renames `ParseCommandFromAnnotations` and removes annotation key arg
* Adds test coverage for `ParseCommandFromAnnotations`
* Table tests
* Adds test coverage for un-parseable templates (un-executable were covered)
This achieves 100% coverage for everything except `execute()`, which has zero test coverage within the package itself. Shouldn't be too tricky to test but ran out of time today.
=> Refactor `Command` parsing

go.mod, go.sum, internal/command/command.go, internal/command/command_test.go, internal/command/commands.go, internal/command/output.go, internal/command/outputs.go, internal/command/outputs_test.go, internal/command/run.go
Refactors the `Execute()` method of `Command` and surrounding code:
* Removes `Stderr` from `Outputs` entirely, moving towards considering outputs as logical outputs rather than terminal outputs. 
* Adds `Append()` to `Outputs` to handle copy and add without mutation
* Adds test coverage for `Execute` in various configurations
* Strips ANSI in tests for simpler assertions, but tests could assert styles later
There are some potential behavioral changes I spotted, such as sending stdout from the command to stderr of the main program when verbose is enabled. But we can propose/discuss those changes with test coverage in place.
=> Refactor `Command` execution

.golangci.yml, cmd/forward.go, go.mod, internal/forwarder/client.go, internal/forwarder/rest.go
I noticed that the user agent is set to a default for the factory runtime.Object request. 
```
kubectl-exec-forward/dev
kubectl-exec-forward/v0.0.0 (darwin/amd64) kubernetes/$Format
```
Changes:
- Moves the client.factory creation into Init, instead of on the New func for the client to take advantage of the passed version string used for the clientset. The factory is used to fetch the generic runtime.Object to handle generic TYPE resources in the CLI arguments.
- Adds an implementation of the `genericclioptions.RESTClientGetter` interface, ensuring that UserAgent is set on the returned rest config.
The stack:
- standard kubectl flags parsed into a generic REST getter([kubect-exec-forward/cmd/forward.go](https://github.com/TakeScoop/kubectl-exec-forward/blob/master/cmd/forward.go#L22))
- …
=> Fix user agent not set properly for factory requests

.github/workflows/test.yml
This was a holdover from separate build and deps caches.
=> actions: fix extraneous go cache key

internal/command/command.go, internal/command/command_test.go, internal/command/commands.go, internal/command/commands_test.go, internal/command/run.go
* Moves `Command` output logic to `Commands`. All `Command` will return output, the `Commands` sequence contains the logic that a command with `ID` has output another `Command` could care about.
* Adds tests for `Execute()` for `Commands` covering migrated output logic
This brings coverage for the `command` package up to nearly 100% outside of `run.go`. In maybe 1-2 more PRs for this round of refactoring, I'll separate out annotation parsing into its own package that depends on `commands` and then `run.go` to its own `execforward` (i.e. main) package with tests.
Separately, `package forwarder` could use some coverage as well.
=> Test `Commands`, move output merging logic up

cmd/forward.go, cmd/forward_test.go, internal/command/command.go, internal/command/command_test.go, internal/command/commands.go, internal/command/commands_test.go, internal/command/run.go, internal/forwarder/client.go
Passes around `IOStreams` values rather than pointers. `IOStreams` is a struct of interfaces:
https://pkg.go.dev/k8s.io/cli-runtime/pkg/genericclioptions#IOStreams
Structs of pointers can generally be passed by value, which slightly simplifies the code. And for this reason, test helper methods in `genericclioptions` return a streams value and not `*IOStreams`.
<hr>
When we pass around structs by value, their contents are copied. If those contents are values, this means that the received struct cannot mutate the passed value, only return a new modified copy:
https://go.dev/play/p/Y_HaqaOcm8u
However, if we introduce struct pointers inside those values the overall behavior changes:
https://go.dev/play/p/0XO3w2qg4qq
Values are still passed by copy, but now the field in the struct is a …
=> pass `genericclioptions.IOStreams` as value

.github/workflows/test.yml
I've installed the Codecov app for our org. For now, the integration is only accessible for public repos. Uploading coverage for public repos does not require authentication.
=> Upload coverage data to codecov

.github/workflows/lint.yml, .golangci.yml
`exhaustruct` replaces `exhaustivestruct`. `nonamedreturns` suggests return signatures have identifiers in addition to types. Both are disruptive and don't make sense as defaults.
=> disable exhaustruct and nonamedreturns linters

.github/workflows/test.yml
When testing this repository, instead of using a hardcoded Go version (1.17), this reads the version declared in `go.mod` using new-ish functionality in `actions/setup-go`. While the former has to be updated manually, Renovate can update `go.mod` (eg, #110). This should resolve the failing checks in #114, which are seemingly failing because of the older Go version being used to invoke the tests.
Additionally, this also enables `actions/setup-go`'s built-in caching rather than calling `actions/cache` separately as was previously required.
=> go: enable version file, built-in caching

.github/workflows/lint.yml, cmd/doc.go, internal/annotation/doc.go, internal/command/command.go, internal/command/doc.go, internal/execforward/doc.go, internal/forwarder/doc.go, internal/forwarder/ports.go, internal/forwarder/ports_test.go, main.go
Same as #115, but for the linting workflow. Also updates the linter, since Go 1.18 introduces some notable changes (including generics) with evolving support in golangci-lint.
Upgrading the linter raised some new warnings, which I've resolved here. In the case where this required a change to code and not just formatting, I've added test coverage against the modified function where previously there was none.
=> go: use version file for lint, update golangci-lint

.github/workflows/release.yml
A corresponding update to #115 which uses the same Go version used for testing to release. Currently, the release process is failing because the release build is attempted with an incompatible Go version.
=> release: use go version from `go.mod`
